# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Transfer.delete_all

User.create(username: "AkramDriscoll", display_name: "Akram Driscoll", password: "test", password_confirm: "test")
User.create(username: "EliseCallahan", display_name: "Elise Callahan", password: "test", password_confirm: "test")
User.create(username: "HectorTravis", display_name: "Hector Travis", password: "test", password_confirm: "test")
User.create(username: "AmiCharlton", display_name: "Ami Charlton", password: "test", password_confirm: "test")
User.create(username: "EmaStout", display_name: "Ema Stout", password: "test", password_confirm: "test")
User.create(username: "IndianaZimmerman", display_name: "Indiana Zimmerman", password: "test", password_confirm: "test")
User.create(username: "LillyAnnOsborne", display_name: "Lilly-Ann Osborne", password: "test", password_confirm: "test")
User.create(username: "KajusSellers", display_name: "Kajus Sellers", password: "test", password_confirm: "test")
User.create(username: "MaisieFitzgerald", display_name: "Maisie Fitzgerald", password: "test", password_confirm: "test")
User.create(username: "MahekTyler", display_name: "Mahek Tyler", password: "test", password_confirm: "test")

Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 10),amount: 10, note: "transfer1", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer2", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 2),amount: 10, note: "transfer3", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 8),amount: 10, note: "transfer4", status: "pending")

Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer6", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 7),amount: 10, note: "transfer7", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 1),amount: 10, note: "transfer8", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer9", status: "completed")

Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 10),amount: 10, note: "transfer11", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 9),amount: 10, note: "transfer12", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 8),amount: 10, note: "transfer13", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 8),amount: 10, note: "transfer14", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer15", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 4),amount: 10, note: "transfer16", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 9),amount: 10, note: "transfer17", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer18", status: "pending")

Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer20", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 3),amount: 10, note: "transfer21", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer22", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 1),amount: 10, note: "transfer23", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer24", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer25", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 6),amount: 10, note: "transfer26", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 7),amount: 10, note: "transfer27", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer28", status: "completed")

Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer30", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 3),amount: 10, note: "transfer31", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 1),amount: 10, note: "transfer32", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer33", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 5),amount: 10, note: "transfer34", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer35", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer36", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 10),amount: 10, note: "transfer37", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer38", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 5),amount: 10, note: "transfer39", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer40", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer41", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 5),amount: 10, note: "transfer42", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 10),amount: 10, note: "transfer43", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 2),amount: 10, note: "transfer44", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer45", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 3),amount: 10, note: "transfer46", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 2),amount: 10, note: "transfer47", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 9),amount: 10, note: "transfer48", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer49", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 2),amount: 10, note: "transfer50", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 5),amount: 10, note: "transfer51", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 3),amount: 10, note: "transfer52", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer53", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 6),amount: 10, note: "transfer54", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 8),amount: 10, note: "transfer55", status: "completed")

Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 4),amount: 10, note: "transfer57", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 9),amount: 10, note: "transfer58", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 6),amount: 10, note: "transfer59", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 4),amount: 10, note: "transfer60", status: "completed")

Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer62", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer63", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 2),amount: 10, note: "transfer64", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 6),amount: 10, note: "transfer65", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer66", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer67", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 2),amount: 10, note: "transfer68", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 7),amount: 10, note: "transfer69", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer70", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer71", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer72", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 9),amount: 10, note: "transfer73", status: "completed")

Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 8),amount: 10, note: "transfer75", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 9),amount: 10, note: "transfer76", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 4),amount: 10, note: "transfer77", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer78", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 4),amount: 10, note: "transfer79", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer80", status: "pending")

Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 5),amount: 10, note: "transfer82", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 9),amount: 10, note: "transfer83", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 9),amount: 10, note: "transfer84", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 2),amount: 10, note: "transfer85", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 6),amount: 10, note: "transfer86", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 1),amount: 10, note: "transfer87", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 9),amount: 10, note: "transfer88", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 2),amount: 10, note: "transfer89", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer90", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer91", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer92", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 3),amount: 10, note: "transfer93", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer94", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 10),amount: 10, note: "transfer95", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 3),amount: 10, note: "transfer96", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 7),amount: 10, note: "transfer97", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 8),amount: 10, note: "transfer98", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer99", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer100", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 10),amount: 10, note: "transfer101", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer102", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer103", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 1),amount: 10, note: "transfer104", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer105", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer106", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 10),amount: 10, note: "transfer107", status: "completed")

Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 2),amount: 10, note: "transfer109", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 2),amount: 10, note: "transfer110", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 3),amount: 10, note: "transfer111", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer112", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 9),amount: 10, note: "transfer113", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer114", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 2),amount: 10, note: "transfer115", status: "completed")

Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 2),amount: 10, note: "transfer117", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer118", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 4),amount: 10, note: "transfer119", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer120", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 3),amount: 10, note: "transfer121", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer122", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer123", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 8),amount: 10, note: "transfer124", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 5),amount: 10, note: "transfer125", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 4),amount: 10, note: "transfer126", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer127", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer128", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 1),amount: 10, note: "transfer129", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 1),amount: 10, note: "transfer130", status: "pending")

Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer132", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 9),amount: 10, note: "transfer133", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer134", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 4),amount: 10, note: "transfer135", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer136", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer137", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer138", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer139", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer140", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 1),amount: 10, note: "transfer141", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer142", status: "pending")


Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer145", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer146", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer147", status: "completed")

Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 10),amount: 10, note: "transfer149", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 10),amount: 10, note: "transfer150", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 6),amount: 10, note: "transfer151", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 2),amount: 10, note: "transfer152", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 1),amount: 10, note: "transfer153", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer154", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer155", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer156", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 3),amount: 10, note: "transfer157", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 6),amount: 10, note: "transfer158", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer159", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 2),amount: 10, note: "transfer160", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 5),amount: 10, note: "transfer161", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer162", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer163", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 4),amount: 10, note: "transfer164", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer165", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer166", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer167", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 7),amount: 10, note: "transfer168", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 1),amount: 10, note: "transfer169", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 7),amount: 10, note: "transfer170", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 1),amount: 10, note: "transfer171", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer172", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 5),amount: 10, note: "transfer173", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 5),amount: 10, note: "transfer174", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer175", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 5),amount: 10, note: "transfer176", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 1),amount: 10, note: "transfer177", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer178", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer179", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 7),amount: 10, note: "transfer180", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 6),amount: 10, note: "transfer181", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 3),amount: 10, note: "transfer182", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer183", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 1),amount: 10, note: "transfer184", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 2),amount: 10, note: "transfer185", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer186", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 8),amount: 10, note: "transfer187", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 6),amount: 10, note: "transfer188", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 3),amount: 10, note: "transfer189", status: "completed")

Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 3),amount: 10, note: "transfer191", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer192", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 1),amount: 10, note: "transfer193", status: "pending")

Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 3),amount: 10, note: "transfer195", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 2),amount: 10, note: "transfer196", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 3),amount: 10, note: "transfer197", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer198", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 8),amount: 10, note: "transfer199", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer200", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 6),amount: 10, note: "transfer201", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer202", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer203", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 2),amount: 10, note: "transfer204", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer205", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer206", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer207", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer208", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 5),amount: 10, note: "transfer209", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 10),amount: 10, note: "transfer210", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 8),amount: 10, note: "transfer211", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer212", status: "pending")

Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer214", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 3),amount: 10, note: "transfer215", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer216", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 9),amount: 10, note: "transfer217", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 7),amount: 10, note: "transfer218", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer219", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 7),amount: 10, note: "transfer220", status: "completed")

Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer222", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 7),amount: 10, note: "transfer223", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer224", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer225", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer226", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 4),amount: 10, note: "transfer227", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer228", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 5),amount: 10, note: "transfer229", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer230", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 9),amount: 10, note: "transfer231", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 1),amount: 10, note: "transfer232", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 4),amount: 10, note: "transfer233", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer234", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer235", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer236", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer237", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer238", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer239", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 6),amount: 10, note: "transfer240", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer241", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 7),amount: 10, note: "transfer242", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer243", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer244", status: "completed")

Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 1),amount: 10, note: "transfer246", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 5),amount: 10, note: "transfer247", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer248", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 5),amount: 10, note: "transfer249", status: "completed")

Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer251", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer252", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 8),amount: 10, note: "transfer253", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer254", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 2),amount: 10, note: "transfer255", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 9),amount: 10, note: "transfer256", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 8),amount: 10, note: "transfer257", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 4),amount: 10, note: "transfer258", status: "completed")

Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer260", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer261", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer262", status: "pending")

Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer264", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer265", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer266", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 2),amount: 10, note: "transfer267", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 10),amount: 10, note: "transfer268", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 9),amount: 10, note: "transfer269", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 1),amount: 10, note: "transfer270", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 10),amount: 10, note: "transfer271", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 10),amount: 10, note: "transfer272", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 5),amount: 10, note: "transfer273", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer274", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer275", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer276", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 4),amount: 10, note: "transfer277", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 1),amount: 10, note: "transfer278", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer279", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer280", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 8),amount: 10, note: "transfer281", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 7),amount: 10, note: "transfer282", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer283", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer284", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 2),amount: 10, note: "transfer285", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer286", status: "completed")

Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer288", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 10),amount: 10, note: "transfer289", status: "pending")

Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 3),amount: 10, note: "transfer291", status: "completed")


Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 4),amount: 10, note: "transfer294", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer295", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer296", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 7),amount: 10, note: "transfer297", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 10),amount: 10, note: "transfer298", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 6),amount: 10, note: "transfer299", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 5),amount: 10, note: "transfer300", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer301", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer302", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 5),amount: 10, note: "transfer303", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer304", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 10),amount: 10, note: "transfer305", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer306", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer307", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer308", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer309", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 5),amount: 10, note: "transfer310", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 9),amount: 10, note: "transfer311", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 4),amount: 10, note: "transfer312", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 6),amount: 10, note: "transfer313", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 1),amount: 10, note: "transfer314", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer315", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 1),amount: 10, note: "transfer316", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer317", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 10),amount: 10, note: "transfer318", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 5),amount: 10, note: "transfer319", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 10),amount: 10, note: "transfer320", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 1),amount: 10, note: "transfer321", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 3),amount: 10, note: "transfer322", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 8),amount: 10, note: "transfer323", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 2),amount: 10, note: "transfer324", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer325", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer326", status: "completed")


Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer329", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 9),amount: 10, note: "transfer330", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 6),amount: 10, note: "transfer331", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 4),amount: 10, note: "transfer332", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer333", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer334", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer335", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 1),amount: 10, note: "transfer336", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 10),amount: 10, note: "transfer337", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 6),amount: 10, note: "transfer338", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer339", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 2),amount: 10, note: "transfer340", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 5),amount: 10, note: "transfer341", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 3),amount: 10, note: "transfer342", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer343", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 1),amount: 10, note: "transfer344", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 3),amount: 10, note: "transfer345", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 5),amount: 10, note: "transfer346", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer347", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 7),amount: 10, note: "transfer348", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer349", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 2),amount: 10, note: "transfer350", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer351", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer352", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer353", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer354", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer355", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 7),amount: 10, note: "transfer356", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 10),amount: 10, note: "transfer357", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 8),amount: 10, note: "transfer358", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 4),amount: 10, note: "transfer359", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 3),amount: 10, note: "transfer360", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer361", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 9),amount: 10, note: "transfer362", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 1),amount: 10, note: "transfer363", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 9),amount: 10, note: "transfer364", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer365", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 1),amount: 10, note: "transfer366", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 6),amount: 10, note: "transfer367", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer368", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer369", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 3),amount: 10, note: "transfer370", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 9),amount: 10, note: "transfer371", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 5),amount: 10, note: "transfer372", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer373", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer374", status: "completed")

Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 7),amount: 10, note: "transfer376", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 10),amount: 10, note: "transfer377", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 4),amount: 10, note: "transfer378", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 7),amount: 10, note: "transfer379", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer380", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 2),amount: 10, note: "transfer381", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 3),amount: 10, note: "transfer382", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 9),amount: 10, note: "transfer383", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 2),amount: 10, note: "transfer384", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer385", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 8),amount: 10, note: "transfer386", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 1),amount: 10, note: "transfer387", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 9),amount: 10, note: "transfer388", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 1),amount: 10, note: "transfer389", status: "pending")

Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer391", status: "completed")

Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 3),amount: 10, note: "transfer393", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 10),amount: 10, note: "transfer394", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 5),amount: 10, note: "transfer395", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 9),amount: 10, note: "transfer396", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer397", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 9),amount: 10, note: "transfer398", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 2),amount: 10, note: "transfer399", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 8),amount: 10, note: "transfer400", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 9),amount: 10, note: "transfer401", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 8),amount: 10, note: "transfer402", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer403", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 3),amount: 10, note: "transfer404", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer405", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 4),amount: 10, note: "transfer406", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 1),amount: 10, note: "transfer407", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 4),amount: 10, note: "transfer408", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer409", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer410", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 7),amount: 10, note: "transfer411", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 6),amount: 10, note: "transfer412", status: "completed")


Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 7),amount: 10, note: "transfer415", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 1),amount: 10, note: "transfer416", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 7),amount: 10, note: "transfer417", status: "completed")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 5),amount: 10, note: "transfer418", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 3),amount: 10, note: "transfer419", status: "pending")

Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 10),amount: 10, note: "transfer421", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer422", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 2),amount: 10, note: "transfer423", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer424", status: "completed")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 8),amount: 10, note: "transfer425", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 9),amount: 10, note: "transfer426", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer427", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer428", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer429", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 9),amount: 10, note: "transfer430", status: "pending")

Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer432", status: "completed")

Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 3),amount: 10, note: "transfer434", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 1),amount: 10, note: "transfer435", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 3),amount: 10, note: "transfer436", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 3),amount: 10, note: "transfer437", status: "completed")

Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer439", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 1),amount: 10, note: "transfer440", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 7),amount: 10, note: "transfer441", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 8),amount: 10, note: "transfer442", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 3),amount: 10, note: "transfer443", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 5),amount: 10, note: "transfer444", status: "pending")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 4),amount: 10, note: "transfer445", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 7),amount: 10, note: "transfer446", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer447", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 2),amount: 10, note: "transfer448", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 7),amount: 10, note: "transfer449", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 8),amount: 10, note: "transfer450", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 10),amount: 10, note: "transfer451", status: "pending")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 6),amount: 10, note: "transfer452", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer453", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 2),amount: 10, note: "transfer454", status: "completed")

Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 7),amount: 10, note: "transfer456", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 3),amount: 10, note: "transfer457", status: "completed")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 3),amount: 10, note: "transfer458", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 8),amount: 10, note: "transfer459", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 2),amount: 10, note: "transfer460", status: "completed")

Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer462", status: "pending")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 2),amount: 10, note: "transfer463", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 4),amount: 10, note: "transfer464", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer465", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer466", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 10),amount: 10, note: "transfer467", status: "pending")
Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 2),amount: 10, note: "transfer468", status: "pending")
Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 9),amount: 10, note: "transfer469", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 5),amount: 10, note: "transfer470", status: "pending")

Transfer.create(receiver: User.find_by(id: 1),sender: User.find_by(id: 8),amount: 10, note: "transfer472", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 8),amount: 10, note: "transfer473", status: "pending")

Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer475", status: "completed")

Transfer.create(receiver: User.find_by(id: 10),sender: User.find_by(id: 3),amount: 10, note: "transfer477", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 7),amount: 10, note: "transfer478", status: "pending")

Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 1),amount: 10, note: "transfer480", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 7),amount: 10, note: "transfer481", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 5),amount: 10, note: "transfer482", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 4),amount: 10, note: "transfer483", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer484", status: "completed")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 10),amount: 10, note: "transfer485", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 1),amount: 10, note: "transfer486", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 6),amount: 10, note: "transfer487", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 3),amount: 10, note: "transfer488", status: "pending")
Transfer.create(receiver: User.find_by(id: 5),sender: User.find_by(id: 3),amount: 10, note: "transfer489", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 5),amount: 10, note: "transfer490", status: "pending")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 7),amount: 10, note: "transfer491", status: "completed")
Transfer.create(receiver: User.find_by(id: 6),sender: User.find_by(id: 4),amount: 10, note: "transfer492", status: "completed")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 6),amount: 10, note: "transfer493", status: "pending")
Transfer.create(receiver: User.find_by(id: 4),sender: User.find_by(id: 8),amount: 10, note: "transfer494", status: "completed")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 3),amount: 10, note: "transfer495", status: "pending")
Transfer.create(receiver: User.find_by(id: 2),sender: User.find_by(id: 9),amount: 10, note: "transfer496", status: "completed")
Transfer.create(receiver: User.find_by(id: 8),sender: User.find_by(id: 1),amount: 10, note: "transfer497", status: "pending")
Transfer.create(receiver: User.find_by(id: 3),sender: User.find_by(id: 2),amount: 10, note: "transfer498", status: "completed")
Transfer.create(receiver: User.find_by(id: 9),sender: User.find_by(id: 1),amount: 10, note: "transfer499", status: "completed")
Transfer.create(receiver: User.find_by(id: 7),sender: User.find_by(id: 10),amount: 10, note: "transfer500", status: "completed")


